name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # NOVO PASSO: Converte o nome do repositório para minúsculas
      - name: Preparar tags da imagem
        id: prep
        run: |
          REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "repo=$REPO" >> $GITHUB_OUTPUT

      - name: Build e Push da imagem
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # USA A VERSÃO EM MINÚSCULAS GERADA NO PASSO ANTERIOR
          tags: ghcr.io/${{ steps.prep.outputs.repo }}:latest

  deploy:
    name: Deploy no Servidor EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Executar comandos de deploy no servidor
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC_PUBLIC_IP }} << 'EOF'
            cd ~/trabalhodevops
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose pull
            docker compose up -d
          EOF
