name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy no Servidor EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Executar comandos de deploy no servidor
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd ~/trabalhodevops
            git pull
            docker compose up --build -d
          EOF