name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy no Servidor EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Executar comandos de deploy no servidor
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            set -euxo pipefail

            # Atualiza pacotes
            sudo apt-get update -y || true

            # Garante git, docker e plugin docker compose
            if ! command -v git >/dev/null 2>&1; then
              sudo apt-get install -y git
            fi
            if ! command -v docker >/dev/null 2>&1; then
              # Para Ubuntu via user_data já deve existir, mas deixamos resiliente
              sudo apt-get install -y docker.io docker-compose
              sudo systemctl enable --now docker
              sudo usermod -aG docker ubuntu || true
            fi

            # Clona ou atualiza o repositório
            if [ ! -d "~/trabalhodevops/.git" ]; then
              rm -rf ~/trabalhodevops || true
              git clone https://github.com/DevOps-Uninter/trabalhodevops.git ~/trabalhodevops
            fi
            cd ~/trabalhodevops
            git pull --rebase --autostash || git fetch --all --prune

            # Tenta docker compose V2 plugin; se falhar, usa docker-compose
            if docker compose version >/dev/null 2>&1; then
              docker compose up --build -d
            else
              if command -v docker-compose >/dev/null 2>&1; then
                docker-compose up --build -d
              else
                echo "docker compose/docker-compose não encontrado" >&2
                exit 1
              fi
            fi
          EOF