name: Verificação de Código

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar ferramentas de linting
        run: |
          pip install flake8 pydocstyle

      - name: Verificar PEP8 com flake8
        run: |
          flake8 app --max-line-length=90

      - name: Verificar docstrings com pydocstyle
        run: |
          pydocstyle app
