name: Smoke SSH

on:
  workflow_dispatch:
    inputs:
      host:
        description: "EC2 public IP or DNS"
        required: true
        type: string
      user:
        description: "SSH user (ubuntu for Ubuntu, ec2-user for Amazon Linux)"
        required: false
        default: "ubuntu"
        type: string

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Show target
        run: |
          echo "Target: ${{ inputs.user }}@${{ inputs.host }}"

      - name: Install netcat
        run: |
          sudo apt-get update -y
          sudo apt-get install -y netcat-openbsd

      - name: Check TCP connectivity to port 22
        run: |
          set -euxo pipefail
          nc -vz -w 5 ${{ inputs.host }} 22 || {
            echo 'Cannot reach port 22 from GitHub runner (likely Security Group/NACL)';
            exit 1;
          }

      - name: Prep SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Try SSH with verbose logging (no command)
        run: |
          set -euxo pipefail
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -vvv ${{ inputs.user }}@${{ inputs.host }} exit || true
          echo "If TCP check passed but SSH failed with Permission denied, the private key does not match the EC2 key pair."
